version: '3.9'

services:
  fe:
    build: ./client
    command: npm run dev
    ports:
      - 8000:8000
    environment:
      - VITE_BACKEND_URL=http://localhost:5000

  be:
    build: ./server
    command: node index.js
    ports:
      - 5000:5000
    environment:
      - MONGODB_URI=mongodb+srv://Savio:fl2SAv1byEEcHMQy@cluster-mern.gnljqnp.mongodb.net/?retryWrites=true&w=majority