version: '3.9'

services:
  fe:
    build: ./client
    command: npm run dev
    ports:
      - 8000:8000

  be:
    build: ./server
    command: node index.js
    ports:
      - 5000:5000
    environment:
      - MONGODB=mongodb://db:27017/mydatabase

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mern:/data/db

volumes:
  mern:
